trigger:
- master

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILD_KIT: 1

strategy:
  matrix:
    aspnet21:
      dotnetVersion: 2.1
    aspnet30:
      dotnetVersion: 3.0
    aspnet31:
      dotnetVersion: 3.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: docker login
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'
- script: |
    mkdir -p $DOCKER_CONFIG/cli-plugins
    curl -J -L -o $DOCKER_CONFIG/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/latest
    chmod a+x $DOCKER_CONFIG/cli-plugins/docker-buildx
  displayName: install buildx extension
- script: |
    docker info
    docker buildx --help
  displayName: docker buildx