trigger:
- master

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILD_KIT: 1

strategy:
  matrix:
    aspnet21:
      dotnetVersion: 2.1
    aspnet30:
      dotnetVersion: 3.0
    aspnet31:
      dotnetVersion: 3.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: docker install
  inputs:
    dockerVersion: '19.03.5'
- task: Docker@2
  displayName: docker login
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'
- script: |
    docker version
    docker info
    docker buildx --help
  displayName: docker buildx