trigger:
- master

strategy:
  matrix:
    aspnet21:
      dotnetVersion: 2.1
    aspnet30:
      dotnetVersion: 3.0
    aspnet31:
      dotnetVersion: 3.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'
- script: |
    docker version