version: '2.0'
services:

  aspnet21:
    build:
      context: .
      args:
        DOTNETVERSION: 2.1
        DOTNETEXTRAFOLDER: /core
    image: petersendev/aspnet:2.1-dev

  aspnet31:
    build:
      context: .
      args:
        DOTNETVERSION: 3.1
        DOTNETEXTRAFOLDER: null
    image: petersendev/aspnet:3.1-dev

  net50:
    build:
      context: .
      args:
        DOTNETVERSION: 5.0
        DOTNETEXTRAFOLDER: null
    image: petersendev/aspnet:5.0-dev

  net60:
    build:
      context: .
      args:
        DOTNETVERSION: 6.0
        DOTNETEXTRAFOLDER: null
    image: petersendev/aspnet:6.0-dev
